apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backstage.yaml
  - postgres.yaml

configMapGenerator:
  - name: backstage-config
    literals:
      - APP_CONFIG_backend_database_client=pg
      - POSTGRES_USER=backstage
      - POSTGRES_DB=backstage

secretGenerator:
  - name: backstage-secrets
    literals:
      - POSTGRES_PASSWORD=backstage
      - BACKEND_SECRET=your-256-bit-secret 